server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/supermall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: renren
    password: 123456
  application:
    name: supermall-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
